FROM nasanccs/spgpu-baselibs:latest

# ----------------------------------------------------------------------------
# https://stereopipeline.readthedocs.io/en/latest/stereo_algorithms.html#adding-new-algorithms-to-asp
# ----------------------------------------------------------------------------

RUN echo "Search for this in the log file to see what happened."

# ----------------------------------------------------------------------------
# Paths
# ----------------------------------------------------------------------------
ARG ilabSource="/usr/local/ilab"
ARG repoName="stereo-pipeline-gpu-plugin"
ARG repoPath=${ilabSource}/${repoName}
ARG build=${ilabSource}/"build"
ARG stereoPipelinePath="/opt/StereoPipeline"
ARG plugInPath=${stereoPipelinePath}/"plugins/stereo"

# ----------------------------------------------------------------------------
# To get the GPU plug-in files, the repository must be cloned.
# ----------------------------------------------------------------------------
RUN mkdir -p ${ilabSource} && \
    git clone --single-branch --branch main \
		https://github.com/nasa-nccs-hpda/${repoName} \
        ${repoPath}

# ----------------------------------------------------------------------------
# Compile the BM plug in and copy it to Stereo Pipeline.
# ----------------------------------------------------------------------------
ARG name="opencv_bm_gpu"
RUN mkdir ${build}

RUN g++ ${repoPath}/spgpu/correlator/${name}.cpp -o ${build}/${name} -I/usr/local/include/opencv4 -I/usr/include/gdal -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_calib3d -lopencv_cudaimgproc -lopencv_cudastereo -lopencv_imgcodecs -lgdal -DHAVE_OPENCV_CUDA=1

ARG dest=${plugInPath}/${name}/bin
RUN mkdir -p ${dest}
COPY ${build}/${name} $dest

# ----------------------------------------------------------------------------
# Remove the cloned repository.
# ----------------------------------------------------------------------------

HEALTHCHECK NONE
ENTRYPOINT []
CMD ["/bin/bash"]
